// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5C5r4ybf4Rr2wNC6xnfdFZ_SYmlliJR8',
    appId: '1:205352381402:web:54a5b3acd30fa7de64aee3',
    messagingSenderId: '205352381402',
    projectId: 'back-to-us-base',
    authDomain: 'back-to-us-base.firebaseapp.com',
    storageBucket: 'back-to-us-base.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDughrlHz4715fm0SsBFa-LIJHPx_cMQl8',
    appId: '1:205352381402:android:56bbc40d0a81b6d664aee3',
    messagingSenderId: '205352381402',
    projectId: 'back-to-us-base',
    storageBucket: 'back-to-us-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFO8jTMRyIhC1HkoDgAibknMSkiRufCmk',
    appId: '1:205352381402:ios:dfc75d0103d9d7b364aee3',
    messagingSenderId: '205352381402',
    projectId: 'back-to-us-base',
    storageBucket: 'back-to-us-base.firebasestorage.app',
    iosBundleId: 'com.example.backToUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFO8jTMRyIhC1HkoDgAibknMSkiRufCmk',
    appId: '1:205352381402:ios:dfc75d0103d9d7b364aee3',
    messagingSenderId: '205352381402',
    projectId: 'back-to-us-base',
    storageBucket: 'back-to-us-base.firebasestorage.app',
    iosBundleId: 'com.example.backToUs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5C5r4ybf4Rr2wNC6xnfdFZ_SYmlliJR8',
    appId: '1:205352381402:web:e39354c93e3a383f64aee3',
    messagingSenderId: '205352381402',
    projectId: 'back-to-us-base',
    authDomain: 'back-to-us-base.firebaseapp.com',
    storageBucket: 'back-to-us-base.firebasestorage.app',
  );
}
